# Generated by Django 4.2.4 on 2024-01-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('year', models.FloatField(blank=True, null=True)),
                ('st_population', models.FloatField(blank=True, null=True)),
                ('total_population', models.FloatField(blank=True, null=True)),
                ('W_BMI', models.FloatField(blank=True, null=True)),
                ('C_UW', models.FloatField(blank=True, null=True)),
                ('AN_W', models.FloatField(blank=True, null=True)),
                ('AN_C', models.FloatField(blank=True, null=True)),
                ('AHC_ANC', models.FloatField(blank=True, null=True)),
                ('AHC_Full_ANC', models.FloatField(blank=True, null=True)),
                ('AHC_PNC', models.FloatField(blank=True, null=True)),
                ('AHC_HI', models.FloatField(blank=True, null=True)),
                ('Enrollment', models.FloatField(blank=True, null=True)),
                ('Equity', models.FloatField(blank=True, null=True)),
                ('E_DropRate', models.FloatField(blank=True, null=True)),
                ('S_Sani', models.FloatField(blank=True, null=True)),
                ('S_CoFu', models.FloatField(blank=True, null=True)),
                ('S_DrWa', models.FloatField(blank=True, null=True)),
                ('S_Elec', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
