# Generated by Django 5.0 on 2024-01-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district_wise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='user',
            new_name='owner',
        ),
    ]
