# Generated by Django 5.0 on 2024-01-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district_wise', '0002_rename_user_district_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='owner',
            new_name='user',
        ),
    ]
