# Generated by Django 4.2.4 on 2024-01-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_wise', '0003_district_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='st_population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='total_population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
