# Generated by Django 5.0 on 2024-01-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district_wise', '0004_alter_district_st_population_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='slug',
        ),
    ]
