# Generated by Django 5.0 on 2024-01-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_wise', '0005_remove_district_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='st_population',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='total_population',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
