# Generated by Django 4.2.4 on 2024-01-27 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('incidence', models.FloatField(blank=True, null=True)),
                ('intensity', models.FloatField(blank=True, null=True)),
                ('tdi', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(default='1234567890', on_delete=django.db.models.deletion.CASCADE, related_name='tribe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Hitcounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_views', models.IntegerField(default=0)),
                ('last_refresh_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tribe_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(upload_to='images/logo_images')),
                ('main_image', models.ImageField(upload_to='images/main_images')),
                ('main_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('village_image', models.ImageField(upload_to='images/village_images')),
                ('village_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('map_image', models.ImageField(upload_to='images/map_images')),
                ('date', models.DateField(blank=True, null=True)),
                ('tribe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tribe_image', to='home.tribe')),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(null=True)),
                ('CD_score', models.BooleanField(blank=True, null=True)),
                ('IM_score', models.BooleanField(blank=True, null=True)),
                ('MC_score', models.BooleanField(blank=True, null=True)),
                ('CM_score', models.BooleanField(blank=True, null=True)),
                ('FS_score', models.BooleanField(blank=True, null=True)),
                ('LE_score', models.BooleanField(blank=True, null=True)),
                ('DRO_score', models.BooleanField(blank=True, null=True)),
                ('IC_score', models.BooleanField(blank=True, null=True)),
                ('OW_score', models.BooleanField(blank=True, null=True)),
                ('SANI_score', models.BooleanField(blank=True, null=True)),
                ('FUEL_score', models.BooleanField(blank=True, null=True)),
                ('DRWA_score', models.BooleanField(blank=True, null=True)),
                ('ELECTR_score', models.BooleanField(blank=True, null=True)),
                ('ASS_score', models.BooleanField(blank=True, null=True)),
                ('LAN_score', models.BooleanField(blank=True, null=True)),
                ('ARTS_score', models.BooleanField(blank=True, null=True)),
                ('EV_score', models.BooleanField(blank=True, null=True)),
                ('MEET_score', models.BooleanField(blank=True, null=True)),
                ('tribeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='household', to='home.tribe')),
            ],
        ),
    ]
