# Generated by Django 4.2.4 on 2024-01-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Hitcounts',
            new_name='User_Hitcount',
        ),
    ]
