# Generated by Django 4.2.4 on 2024-01-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_user_hitcounts_user_hitcount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Hitcount',
            new_name='User_Hitcounts',
        ),
    ]
