# Generated by Django 4.2.4 on 2024-01-28 05:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_rename_user_hitcount_user_hitcounts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tribe',
            unique_together={('user', 'year', 'slug')},
        ),
    ]
