# Generated by Django 4.2.4 on 2024-02-01 07:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_alter_tribe_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tribe',
            unique_together={('user', 'year', 'name')},
        ),
        migrations.RemoveField(
            model_name='tribe',
            name='slug',
        ),
    ]
