# Generated by Django 4.2.4 on 2024-02-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_tribe_image_tribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='village_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
