# Generated by Django 5.0 on 2024-02-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_tribe_user'),
        ('home', '0007_tribe_village_details'),
    ]

    operations = [
    ]
