# Generated by Django 4.2.4 on 2024-01-19 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0029_alter_household_arts_score_alter_household_ass_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='user',
            field=models.ForeignKey(default='1234567890', on_delete=django.db.models.deletion.CASCADE, related_name='households', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='household',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tribe',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='user',
            field=models.ForeignKey(default='1234567890', on_delete=django.db.models.deletion.CASCADE, related_name='tribe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tribe',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tribe_image',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe_image',
            name='main_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tribe_image',
            name='map_image',
            field=models.ImageField(default='image', upload_to='images/map_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tribe_image',
            name='village_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='tribeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='household', to='home.tribe'),
        ),
        migrations.AlterField(
            model_name='tribe_image',
            name='logo_image',
            field=models.ImageField(upload_to='images/logo_images'),
        ),
        migrations.AlterField(
            model_name='tribe_image',
            name='main_image',
            field=models.ImageField(upload_to='images/main_images'),
        ),
        migrations.AlterField(
            model_name='tribe_image',
            name='village_image',
            field=models.ImageField(upload_to='images/village_images'),
        ),
    ]
