# Generated by Django 4.2.4 on 2024-01-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_household_user_household_year_tribe_slug_tribe_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Hitcounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_views', models.IntegerField(default=0)),
                ('last_refresh_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
