# Generated by Django 4.2.4 on 2024-01-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_user_hitcounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='user',
        ),
        migrations.RemoveField(
            model_name='household',
            name='year',
        ),
    ]
