# Generated by Django 5.0 on 2024-01-25 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_household_user_remove_household_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='user',
            field=models.ForeignKey(default='1234567899', on_delete=django.db.models.deletion.CASCADE, related_name='tribe', to=settings.AUTH_USER_MODEL),
        ),
    ]
