# Generated by Django 5.0 on 2024-01-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_tribe_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tribe_image',
            old_name='tribe',
            new_name='tribe_image',
        ),
    ]
