# Generated by Django 5.0 on 2024-01-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_rename_tribe_tribe_image_tribe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tribe_image',
            old_name='tribe_image',
            new_name='tribe',
        ),
    ]
