# Generated by Django 4.2.4 on 2024-01-17 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0038_alter_tribe_image_logo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='user',
            field=models.ForeignKey(default='7219142469', on_delete=django.db.models.deletion.CASCADE, related_name='household', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='household',
            name='year',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
