# Generated by Django 4.2.4 on 2024-01-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_household_user_household_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='user',
        ),
        migrations.RemoveField(
            model_name='household',
            name='year',
        ),
    ]
