# Generated by Django 4.2.4 on 2024-01-17 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0040_remove_household_user_remove_household_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='user',
            field=models.ForeignKey(default='7667605908', on_delete=django.db.models.deletion.CASCADE, related_name='households', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='household',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
