# Generated by Django 4.2.4 on 2024-01-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_household_arts_score_alter_household_ass_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='tribe_name',
        ),
    ]
