# Generated by Django 4.2.4 on 2024-01-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_remove_household_user_remove_household_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
