# Generated by Django 4.2.4 on 2024-01-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_tribe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='tribeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='household', to='home.tribe'),
        ),
    ]
