# Generated by Django 4.2.4 on 2024-01-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_household_size_alter_household_tribeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Hitcounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_views', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
