# Generated by Django 4.2.4 on 2024-01-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_alter_user_hitcounts_site_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_hitcounts',
            name='last_refresh_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
